version: '3.7'

services:
  cubit:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: cubit_access
    expose:
      - '${CUBIT_PORT}'
    ports:
      - '${CUBIT_PORT}:${CUBIT_PORT}'
    env_file:
      - '.env'
    command: "npm run dev"
